# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('patronymic', models.TextField()),
                ('year_of_birth', models.IntegerField()),
                ('code_word', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goods_number', models.PositiveIntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway.Client', verbose_name='client')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('first_name', 'last_name', 'patronymic', 'year_of_birth', 'code_word')]),
        ),
    ]
