# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_word',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.TextField(default=''),
        ),
    ]
