# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_auto_20170106_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='client_id',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='giveaway.Client', verbose_name='client object'),
            preserve_default=False,
        ),
    ]
